### PR TITLE
Bundle deps

### PR DESCRIPTION
**Pull request by elbotho**
@Entkenntnis could you publish a version of this for me? (if it works) 

(or send me your `"build": "ts-node ../../../scripts/build"`)

### CODE REVIEW

**Comment by Entkenntnis** [comment]
this repo has never been published. you can simple point to a github repo in package json like this:

grafik

(replace with your fork)

**Comment by elbotho** [comment]
Ah I see. Thank you.
My request was mostly about the build. I wanted to save time on setting it up…

Could you maybe send me `../../../scripts/build`, and `../../../tsconfig.prod` as a starting point than I "should" be fine (although you are right, it's been a terrible experience setting it up in the frontend so far)

**Comment by Entkenntnis** [comment]
Ah, I actually don't have the build environment anymore - but it should be a "simple" yarn and yarn build within https://github.com/serlo/serlo.org-legacy

**Comment by elbotho** [comment]
ohoh 😮 
ok thank you :)

**Pull request closed without merging**
